version: 1

before:
  hooks:
    - make web

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/kuvasz-io/kuvasz-streamer

  mod: readonly
  gobinary: go

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

    main: ./streamer/

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: default
    vendor: Kuvasz.io
    homepage: https://streamer.kuvasz.io/
    maintainer: Kuvasz <kuvasz@kuvasz.io>
    description: |-
      Kuvasz-Streamer is a Postgres-to-Postgres
      data consolidation and change data capture project.
    license: AGPL-3.0
    formats:
      - deb
      - rpm
    umask: 0o002
    provides:
      - kuvasz-streamer
    contents:
      - src: package/kuvasz-streamer.service
        dst: /usr/lib/systemd/system/kuvasz-streamer.service
      - src: package/etc/
        dst: /etc
        type: tree
    scripts:
      postinstall: package/postinstall.sh
      postremove: package/postremove.sh
    rpm:
      signature:
        key_file: "{{ .Env.HOME }}/private.pgp"
    deb:
      signature:
        key_file: "{{ .Env.HOME }}/private.pgp"

dockers:
- image_templates: ["ghcr.io/kuvasz-io/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/kuvasz-io/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/kuvasz-io/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=AGPL-3.0
- image_templates: ["ghcr.io/kuvasz-io/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/kuvasz-io/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/kuvasz-io/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
- name_template: ghcr.io/kuvasz-io/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/kuvasz-io/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/kuvasz-io/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/kuvasz-io/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/kuvasz-io/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/kuvasz-io/{{ .ProjectName }}:{{ .Version }}-arm64v8
      
changelog:
  disable: true
