version: 1

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/kuvasz-io/kuvasz-streamer

  mod: readonly
  gobinary: go

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

    main: ./cmd/

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: default
    vendor: Kuvasz.io
    homepage: https://streamer.kuvasz.io/
    maintainer: Kuvasz <kuvasz@kuvasz.io>
    description: |-
      Kuvasz-Streamer is a Postgres-to-Postgres
      data consolidation and change data capture project.
    license: AGPL-3.0
    formats:
      - deb
      - rpm
    umask: 0o002
    provides:
      - kuvasz-streamer
    contents:
      - src: package/kuvasz-streamer.service
        dst: /usr/lib/systemd/system/kuvasz-streamer.service
      - src: package/etc/
        dst: /etc
        type: tree
    scripts:
      postinstall: package/postinstall.sh
      postremove: package/postremove.sh
    rpm:
      signature:
        key_file: "{{ .Env.HOME }}/private.pgp"
    deb:
      signature:
        key_file: "{{ .Env.HOME }}/private.pgp"

changelog:
  disable: true
