[server]
name = "kuvasz-streamer"
address = ":8000"
pprof = ""

[logs]
level="debug"
format="text"
source=false

[database]
url = "postgres://kuvasz:kuvasz@127.0.0.1/dest?application_name=kuvasz-streamer"

[app]
map_file = "/etc/kuvasz/map.yaml"

