title: Kuvasz-streamer
email: kuvasz@kuvasz.io
description: >- 
  Kuvasz-streamer is an open source change data capture (CDC)
  project that focuses exclusively on Postgres. It is tightly integrated
  with Postgres Logical Replication to provide high performance, 
  low latency replication.
baseurl: "/kuvasz-streamer" # the subpath of your site, e.g. /blog
url: "https://kuvasz-io.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kuvasz-io

theme: just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
