title: Kuvasz-streamer
email: kuvasz@kuvasz.io
description: >- 
  Kuvasz-streamer is an open source change data capture (CDC)
  project that focuses exclusively on Postgres. It is tightly integrated
  with Postgres Logical Replication to provide high performance, 
  low latency replication.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://streamer.kuvasz.io" 
github_username:  kuvasz-io
theme: just-the-docs
color_scheme: wider
plugins:
  - jekyll-feed
ga_tracking: G-R854TNLS2V

nav_external_links:
  - title: Test report
    url: /report.html
