title: Kuvasz-streamer
email: kuvasz@kuvasz.io
description: >- 
  Kuvasz-streamer is an open source change data capture (CDC)
  project that focuses exclusively on Postgres. It is tightly integrated
  with Postgres Logical Replication to provide high performance, 
  low latency replication.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://streamer.kuvasz.io" 
github_username:  kuvasz-io
theme: just-the-docs
color_scheme: wider
plugins:
  - jekyll-feed
ga_tracking: G-R854TNLS2V
logo: /assets/images/logo.png
favicon_ico: /assets/images/favicon.ico
footer_content: "Copyright &copy; 2024-2025 <a href=\"https://kuvasz.io/about/\">George Yazbek</a>. Distributed by an <a href=\"https://github.com/kuvasz-io/kuvasz-streamer/tree/main/LICENSE\">AGPL license.</a>"
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.4.1"

nav_external_links:
  - title: Functional test report
    url: /report.html
  - title: Load test report
    url: https://kuvasz.io/kuvasz-streamer-load-test/
  - title: Github
    url: https://github.com/kuvasz-io/kuvasz-streamer
  - title: Kuvasz Tech blog
    url: https://kuvasz.io