name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Build and publish docs
      run: make docs
    - name: Web
      run: make web
    - name: Vet
      run: make check
    - name: Build
      run: make build
    - name: Run tests
      run: make test
    

