name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Release
      run: goreleaser release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NFPM_DEFAULT_PASSPHRASE: ${{ secrets.NFPM_DEFAULT_PASSPHRASE }}
    - name: Copy packages to repository
      run: cp dist/*.rpm /var/www/caddy/rpm
    - name: Generate RPM repository
      run: cd /var/www/caddy/rpm; createrepo_c -v .
    - name: Add new packages to APT repo
      run: aptly repo add kuvasz dist/*.deb
    - name: Publish APT repository
      run: "aptly publish update stable filesystem:caddy:"
      

