name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Release
      run: goreleaser release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

